name: CI

on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [13]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install firebase tools
        run: npm install -g firebase-tools
      - name: Install required packages
        run: npm install
      - name: Deploy firebase functions
        run: >-
          firebase use $PROJECT_NAME &&
          firebase functions:config:set
          MONGO_URI="${{secrets.MONGO_URI}}"
           &&
          firebase deploy --only functions:api
        env:
          PROJECT_NAME: food-random-265418
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
